title: MeruData Documentation
email: info@merudata.com
theme: minima
plugins:
  - jekyll-feed


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Help.md
  - User_Guides.md
  - Password_Reset_User.md
  - Processing_a_DSAR_User_Guide.md
 
 

# Custom headers
webrick:
  headers:
    Content-Security-Policy:  script-src 'self'; connect-src 'self'; img-src 'self';  
    My-Other-Header: My-Other-Value
