title: MeruData Documentation
email: info@merudata.com
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown 
domain: sriharigoud087.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://sriharigoud087.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /sriharigoud087.github.io/ 


# Custom headers
webrick:
  headers:
    Content-Security-Policy:  script-src 'self'; connect-src 'self'; img-src 'self';  
    My-Other-Header: My-Other-Value
