title: MeruData Documentation
email: info@merudata.com
theme: minima
plugins:
  - jekyll-feed

baseurl: "/md_blog"
url: "https://sriharigoud87.github.io"



lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge



topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
